//! Linux TUN / VPN mode for Aethery.
//!
//! Aether itself only exposes a local SOCKS5 (+ optional HTTP) proxy — there
//! is no TUN device on its side. VPN mode closes that gap by layering a
//! `tun2socks` forwarder ([hev-socks5-tunnel](https://github.com/heiher/hev-socks5-tunnel),
//! bundled as the `hev` sidecar next to `aether`) between a kernel TUN
//! interface and Aether's SOCKS port, then moving the system default route
//! and DNS onto that interface:
//!
//! ```text
//! apps ──► default route ──► aether0 (TUN) ──► hev ──► 127.0.0.1:1819 ──► aether ──► internet
//! ```
//!
//! Routing loops are avoided with a firewall mark: Aether is launched with
//! `--mark <TUN_FWMARK>` (see [`crate::aether::profiles`]) and an
//! `ip rule fwmark … table main` exception keeps marked packets on the real
//! uplink instead of looping them back into the TUN. The privileged half
//! (interface creation, routes, `/etc/resolv.conf`) runs through one-shot
//! `pkexec` scripts so the GUI itself never runs as root — the user gets a
//! single polkit prompt per connect/disconnect.
//!
//! Linux-only by design: other platforms get a clear error from the command
//! layer and the profile flag is ignored in `as_args()` off Linux.

use crate::events::{now_millis, LogEvent, LOG_EVENT};
use serde::Serialize;
use std::path::{Path, PathBuf};
use std::time::{Duration, Instant};
use tauri::{AppHandle, Emitter, Manager};

/// Kernel interface name. Deliberately NOT `tun0` — test machines (and other
/// VPNs) commonly already own `tun0`, and colliding with it would hijack or
/// break an unrelated tunnel.
pub const TUN_NAME: &str = "aether0";
/// Address assigned to the TUN interface (hev-socks5-tunnel convention:
/// documentation/reserved TEST-NET-2 space, never routed publicly).
pub const TUN_IPV4: &str = "198.18.0.1";
pub const TUN_MTU: u32 = 1500;
/// Firewall mark shared by Aether's `--mark` and hev's `mark:` — packets
/// carrying it bypass the TUN via `ip rule … table main`.
pub const TUN_FWMARK: u32 = 0x9e;
pub const TUN_FWMARK_STR: &str = "0x9e";
/// DNS used for the system resolver while the VPN is up when the profile has
/// no explicit `dns` value (mirrors Aether's own default).
pub const FALLBACK_DNS: &str = "1.1.1.1,1.0.0.1";

const HEV_PID_FILE: &str = "hev.pid";
const HEV_CONFIG_FILE: &str = "hev-tunnel.yml";
const HEV_LOG_FILE: &str = "hev.log";

#[derive(Serialize, Clone, Debug)]
pub struct VpnStatus {
    pub active: bool,
    pub iface: String,
    pub detail: String,
}

fn data_dir(app: &AppHandle) -> PathBuf {
    app.path()
        .app_data_dir()
        .unwrap_or_else(|_| std::env::temp_dir())
}

/// Locate a bundled resource binary, falling back to the source tree so
/// `tauri dev` works without a bundle install.
fn resolve_resource(app: &AppHandle, dir: &str, name: &str) -> Option<PathBuf> {
    if let Ok(res) = app.path().resource_dir() {
        let p = res.join(dir).join(name);
        if p.exists() {
            return Some(p);
        }
    }
    // Dev fallback: <repo>/src-tauri/<dir>/<name> next to Cargo.toml.
    let dev = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join(dir)
        .join(name);
    if dev.exists() {
        return Some(dev);
    }
    None
}

fn resolve_hev(app: &AppHandle) -> Result<PathBuf, String> {
    let p = resolve_resource(app, "binaries", "hev").ok_or_else(|| {
        "tun2socks binary not found (run src-tauri/binaries/fetch-hev.sh)".to_string()
    })?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(&p, std::fs::Permissions::from_mode(0o755));
    }
    Ok(p)
}

fn resolve_script(app: &AppHandle, name: &str) -> Result<PathBuf, String> {
    resolve_resource(app, "scripts", name)
        .ok_or_else(|| format!("VPN helper script missing: scripts/{name}"))
}

fn emit_log(app: &AppHandle, line: String) {
    let _ = app.emit(
        LOG_EVENT,
        &LogEvent {
            line,
            timestamp: now_millis(),
        },
    );
}

/// Split `--bind`-style `host:port` into the dial target for hev. A `0.0.0.0`
/// (LAN-share) bind is dialed back over loopback — hev must not aim at the
/// wildcard address itself.
pub fn socks_target(bind_address: &str) -> (String, u16) {
    if let Ok(sock) = bind_address.parse::<std::net::SocketAddr>() {
        let host = if sock.ip().is_unspecified() {
            "127.0.0.1".to_string()
        } else {
            sock.ip().to_string()
        };
        return (host, sock.port());
    }
    ("127.0.0.1".to_string(), 1819)
}

fn hev_config(host: &str, port: u16, data: &Path) -> String {
    format!(
        "# Generated by Aethery VPN mode — do not edit (regenerated per connect).\n\
         tunnel:\n\
         \x20 name: {iface}\n\
         \x20 mtu: {mtu}\n\
         \x20 multi-queue: false\n\
         \x20 ipv4: {addr}\n\
         socks5:\n\
         \x20 address: {host}\n\
         \x20 port: {port}\n\
         \x20 udp: 'udp'\n\
         \x20 mark: {mark}\n\
         misc:\n\
         \x20 log-file: '{log}'\n\
         \x20 log-level: warn\n\
         \x20 task-stack-size: 86016\n",
        iface = TUN_NAME,
        mtu = TUN_MTU,
        addr = TUN_IPV4,
        host = host,
        port = port,
        mark = TUN_FWMARK,
        log = data.join(HEV_LOG_FILE).display(),
    )
}

fn pid_alive(data: &Path) -> bool {
    let pid: i32 = std::fs::read_to_string(data.join(HEV_PID_FILE))
        .ok()
        .and_then(|s| s.trim().parse().ok())
        .unwrap_or(0);
    pid > 0 && Path::new(&format!("/proc/{pid}")).exists()
}

fn iface_exists() -> bool {
    std::process::Command::new("ip")
        .args(["link", "show", TUN_NAME])
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Unprivileged liveness check — safe to call anywhere, never prompts.
pub fn is_up(app: &AppHandle) -> bool {
    pid_alive(&data_dir(app)) && iface_exists()
}

pub fn status(app: &AppHandle) -> VpnStatus {
    let data = data_dir(app);
    let alive = pid_alive(&data);
    let iface = iface_exists();
    let (active, detail) = match (alive, iface) {
        (true, true) => (true, format!("TUN {TUN_NAME} via hev-socks5-tunnel")),
        (true, false) => (false, "hev running but interface missing".into()),
        (false, true) => (
            false,
            format!("stale {TUN_NAME} interface, hev not running"),
        ),
        (false, false) => (false, "down".into()),
    };
    VpnStatus {
        active,
        iface: TUN_NAME.into(),
        detail,
    }
}

/// Run `pkexec sh <script> <args…>` with a hard timeout, forwarding output
/// lines into the app log. Returns the script's stdout on success.
fn run_privileged(
    app: &AppHandle,
    script: &Path,
    args: &[String],
    timeout_secs: u64,
) -> Result<String, String> {
    if !cfg!(target_os = "linux") {
        return Err("VPN mode is Linux-only".into());
    }
    let mut child = std::process::Command::new("pkexec")
        .arg("sh")
        .arg(script)
        .args(args)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .map_err(|e| format!("pkexec failed to start ({e}); is polkit installed?"))?;

    let deadline = Instant::now() + Duration::from_secs(timeout_secs);
    loop {
        match child.try_wait() {
            Ok(Some(_)) => break,
            Ok(None) if Instant::now() >= deadline => {
                let _ = child.kill();
                return Err("privileged VPN step timed out".into());
            }
            Ok(None) => std::thread::sleep(Duration::from_millis(200)),
            Err(e) => return Err(format!("waiting on pkexec: {e}")),
        }
    }
    let out = child
        .wait_with_output()
        .map_err(|e| format!("reading pkexec output: {e}"))?;
    let stdout = String::from_utf8_lossy(&out.stdout).to_string();
    let stderr = String::from_utf8_lossy(&out.stderr).to_string();
    for line in stdout.lines().chain(stderr.lines()) {
        let line = line.trim();
        if !line.is_empty() {
            emit_log(app, format!("[tun] {line}"));
        }
    }
    if out.status.success() {
        Ok(stdout)
    } else {
        Err(format!(
            "privileged VPN step failed ({}): {}",
            out.status,
            stderr.lines().next().unwrap_or("see log").trim()
        ))
    }
}

/// Bring the TUN up after Aether's SOCKS port is live. Returns true when
/// traffic is actually flowing through the TUN; false keeps the session as a
/// plain proxy (never fails the connection — a VPN setup problem must not
/// kill a working proxy).
pub fn bring_up(app: &AppHandle, bind_address: &str, dns: &str) -> bool {
    let data = data_dir(app);
    if let Err(e) = std::fs::create_dir_all(&data) {
        emit_log(app, format!("[tun] cannot use data dir: {e}"));
        return false;
    }
    if is_up(app) {
        emit_log(app, format!("[tun] {TUN_NAME} already up"));
        return true;
    }
    let hev = match resolve_hev(app) {
        Ok(p) => p,
        Err(e) => {
            emit_log(app, format!("[tun] {e}"));
            return false;
        }
    };
    let script = match resolve_script(app, "tun-up.sh") {
        Ok(p) => p,
        Err(e) => {
            emit_log(app, format!("[tun] {e}"));
            return false;
        }
    };
    let (host, port) = socks_target(bind_address);
    let cfg = hev_config(&host, port, &data);
    if let Err(e) = std::fs::write(data.join(HEV_CONFIG_FILE), &cfg) {
        emit_log(app, format!("[tun] cannot write hev config: {e}"));
        return false;
    }
    let dns_csv = {
        let d = dns.trim();
        if d.is_empty() {
            FALLBACK_DNS.to_string()
        } else {
            d.to_string()
        }
    };
    emit_log(
        app,
        format!("[tun] bringing up {TUN_NAME} via 127.0.0.1:{port} (polkit prompt expected)…"),
    );
    let args = vec![
        data.display().to_string(),
        hev.display().to_string(),
        data.join(HEV_CONFIG_FILE).display().to_string(),
        TUN_NAME.to_string(),
        TUN_FWMARK_STR.to_string(),
        dns_csv,
    ];
    match run_privileged(app, &script, &args, 120) {
        Ok(_) if is_up(app) => {
            emit_log(
                app,
                format!("[tun] {TUN_NAME} up — system traffic via tunnel"),
            );
            true
        }
        Ok(_) => {
            emit_log(
                app,
                "[tun] setup ran but interface is not up — proxy still works".into(),
            );
            false
        }
        Err(e) => {
            emit_log(
                app,
                format!("[tun] not activated ({e}) — proxy still works"),
            );
            false
        }
    }
}

/// Tear the TUN down. Best-effort and prompt-free when already down.
pub fn bring_down(app: &AppHandle) {
    if !pid_alive(&data_dir(app)) && !iface_exists() {
        return;
    }
    let script = match resolve_script(app, "tun-down.sh") {
        Ok(p) => p,
        Err(e) => {
            emit_log(app, format!("[tun] {e}"));
            return;
        }
    };
    let data = data_dir(app);
    let args = vec![
        data.display().to_string(),
        TUN_NAME.to_string(),
        TUN_FWMARK_STR.to_string(),
    ];
    match run_privileged(app, &script, &args, 30) {
        Ok(_) => emit_log(app, format!("[tun] {TUN_NAME} down — routes/DNS restored")),
        Err(e) => emit_log(app, format!("[tun] teardown issue ({e})")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loopback_bind_targets_loopback() {
        assert_eq!(socks_target("127.0.0.1:1819"), ("127.0.0.1".into(), 1819));
    }

    #[test]
    fn wildcard_bind_dials_back_over_loopback() {
        assert_eq!(socks_target("0.0.0.0:1919"), ("127.0.0.1".into(), 1919));
    }

    #[test]
    fn garbage_bind_falls_back_to_default() {
        assert_eq!(socks_target("127.0.0.1:"), ("127.0.0.1".into(), 1819));
    }

    #[test]
    fn config_points_at_socks_and_names_tun() {
        let cfg = hev_config("127.0.0.1", 1819, Path::new("/tmp/x"));
        assert!(cfg.contains("name: aether0"), "{cfg}");
        assert!(cfg.contains("address: 127.0.0.1"), "{cfg}");
        assert!(cfg.contains("port: 1819"), "{cfg}");
        assert!(cfg.contains("mark: 158"), "{cfg}");
    }
}
